# Generated by Django 3.2.9 on 2021-11-28 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_time_tracker', '0002_task_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_mins',
            field=models.IntegerField(null=True),
        ),
    ]
