# Generated by Django 3.2.9 on 2021-11-28 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_time_tracker', '0003_alter_task_actual_mins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='completed_date',
            field=models.DateTimeField(null=True),
        ),
    ]
