# Generated by Django 3.2.9 on 2021-12-30 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_time_tracker', '0006_alter_task_task_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='actual_mins',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
