# Generated by Django 3.2.9 on 2022-01-11 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('task_time_tracker', '0012_project_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='TaskStatusChange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_datetime', models.DateTimeField(blank=True, null=True)),
                ('inactive_datetime', models.DateTimeField(blank=True, null=True)),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='task_time_tracker.task')),
            ],
        ),
    ]
