# Generated by Django 3.2.9 on 2022-01-12 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task_time_tracker', '0013_taskstatuschange'),
    ]

    operations = [
        migrations.AddField(
            model_name='taskstatuschange',
            name='completed_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
