# Generated by Django 3.2.9 on 2022-01-15 18:54

from django.db import migrations

def change_user_type(apps, schema_editor):
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ct = ContentType.objects.filter(
        app_label='auth',
        model='User'
    ).first()
    if ct:
        ct.app_label = 'task_time_tracker'
        ct.save()

class Migration(migrations.Migration):

    dependencies = [
        ('task_time_tracker', '0014_taskstatuschange_completed_datetime'),
    ]

    operations = [
        migrations.RunPython(change_user_type),
    ]
